version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      ENV: development
      FILL: false
      MIGRATIONS: file://migration
      DSN: postgres://postgres:s123@db:5432/classroom_app?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: classroom_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: