### Create Classroom
POST localhost:8080/class
Content-Type: application/json

{
  "name": "GoLang application development"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Classroom
GET localhost:8080/class/4

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Menu Item
PUT localhost:8080/class/4
Content-Type: application/json

{
  "name": "Updated"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Menu Item
DELETE localhost:8080/class/4
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}