### Create Classroom
POST localhost:8080/class
Content-Type: application/json

{
  "name": "GoLang application development",
  "description": "Golang class"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Classroom
GET localhost:8080/class/5

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update classroom
PUT localhost:8080/class/2
Content-Type: application/json

{
  "name": "Golang application dev",
  "description": "upd"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Classroom
DELETE localhost:8080/class/2
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}